# Generated by Django 4.1.4 on 2022-12-10 01:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("img", models.ImageField(upload_to="")),
                ("img_filename", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
