# Generated by Django 4.1.4 on 2022-12-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="thumb",
            field=models.ImageField(default="deleteme", upload_to=""),
            preserve_default=False,
        ),
    ]
