# Generated by Django 4.1.4 on 2022-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0002_picture_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="picture",
            name="thumb",
            field=models.ImageField(height_field="height", upload_to="", width_field="width"),
        ),
    ]
