# Generated by Django 4.1.4 on 2022-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0003_picture_height_picture_width_alter_picture_thumb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="height",
            new_name="thumb_height",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="width",
            new_name="thumb_width",
        ),
        migrations.AddField(
            model_name="picture",
            name="img_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="img_width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="picture",
            name="img",
            field=models.ImageField(height_field="img_height", upload_to="", width_field="img_width"),
        ),
        migrations.AlterField(
            model_name="picture",
            name="thumb",
            field=models.ImageField(height_field="thumb_height", upload_to="", width_field="thumb_width"),
        ),
    ]
